/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        googleSans: ['GoogleSans', 'sans-serif'],
        googleSansItalic: ['GoogleSans-Italic', 'sans-serif'],
        googleSansMedium: ['GoogleSans-Medium', 'sans-serif'],
        googleSansMediumItalic: ['GoogleSans-MediumItalic', 'sans-serif'],
        googleSansSemiBold: ['GoogleSans-SemiBold', 'sans-serif'],
        googleSansSemiBoldItalic: ['GoogleSans-SemiBoldItalic', 'sans-serif'],
        googleSansBold: ['GoogleSans-Bold', 'sans-serif'],
        googleSansBoldItalic: ['GoogleSans-BoldItalic', 'sans-serif'],
        beVietnamPro: ['BeVietnamPro', 'sans-serif'],
        beVietnamProItalic: ['BeVietnamPro-Italic', 'sans-serif'],
        beVietnamProMedium: ['BeVietnamPro-Medium', 'sans-serif'],
        beVietnamProMediumItalic: ['BeVietnamPro-MediumItalic', 'sans-serif'],
        beVietnamProSemiBold: ['BeVietnamPro-SemiBold', 'sans-serif'],
        beVietnamProSemiBoldItalic: ['BeVietnamPro-SemiBoldItalic', 'sans-serif'],
        beVietnamProBold: ['BeVietnamPro-Bold', 'sans-serif'],
        beVietnamProBoldItalic: ['BeVietnamPro-BoldItalic', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        robotoItalic: ['Roboto-Italic', 'sans-serif'],
        robotoMedium: ['Roboto-Medium', 'sans-serif'],
        robotoMediumItalic: ['Roboto-MediumItalic', 'sans-serif'],
        robotoSemiBold: ['Roboto-SemiBold', 'sans-serif'],
        robotoSemiBoldItalic: ['Roboto-SemiBoldItalic', 'sans-serif'],
        robotoBold: ['Roboto-Bold', 'sans-serif'],
        robotoBoldItalic: ['Roboto-BoldItalic', 'sans-serif'],
      },
      fontSize: {
        xxs: ['10px', { lineHeight: '16px' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '40px' }],
        '4xl': ['36px', { lineHeight: '48px' }],
        '5xl': ['48px', { lineHeight: '64px' }],
      },
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: 'var(--color-card)',
        'card-foreground': 'var(--color-card-foreground)',
        popover: 'var(--color-popover)',
        'popover-foreground': 'var(--color-popover-foreground)',
        primary: 'var(--color-primary)',
        'primary-foreground': 'var(--color-primary-foreground)',
        secondary: 'var(--color-secondary)',
        'secondary-foreground': 'var(--color-secondary-foreground)',
        muted: 'var(--color-muted)',
        'muted-foreground': 'var(--color-muted-foreground)',
        accent: 'var(--color-accent)',
        'accent-foreground': 'var(--color-accent-foreground)',
        destructive: 'var(--color-destructive)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        'chart-1': 'var(--color-chart-1)',
        'chart-2': 'var(--color-chart-2)',
        'chart-3': 'var(--color-chart-3)',
        'chart-4': 'var(--color-chart-4)',
        'chart-5': 'var(--color-chart-5)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-foreground': 'var(--color-sidebar-foreground)',
        'sidebar-primary': 'var(--color-sidebar-primary)',
        'sidebar-primary-foreground': 'var(--color-sidebar-primary-foreground)',
        'sidebar-accent': 'var(--color-sidebar-accent)',
        'sidebar-accent-foreground': 'var(--color-sidebar-accent-foreground)',
        'sidebar-border': 'var(--color-sidebar-border)',
        'sidebar-ring': 'var(--color-sidebar-ring)',
      },
      borderRadius: {
        sm: 6,
        md: 8,
        lg: 10,
        xl: 14,
        '2xl': 18,
        '3xl': 22,
        '4xl': 26,
      },
    },
  },
  plugins: [],
};
