/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        googleSans: ['GoogleSans', 'sans-serif'],
        googleSansItalic: ['GoogleSans-Italic', 'sans-serif'],
        googleSansMedium: ['GoogleSans-Medium', 'sans-serif'],
        googleSansMediumItalic: ['GoogleSans-MediumItalic', 'sans-serif'],
        googleSansSemiBold: ['GoogleSans-SemiBold', 'sans-serif'],
        googleSansSemiBoldItalic: ['GoogleSans-SemiBoldItalic', 'sans-serif'],
        googleSansBold: ['GoogleSans-Bold', 'sans-serif'],
        googleSansBoldItalic: ['GoogleSans-BoldItalic', 'sans-serif'],
      },
      fontSize: {
        xxs: ['10px', { lineHeight: '16px' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '40px' }],
        '4xl': ['36px', { lineHeight: '48px' }],
        '5xl': ['48px', { lineHeight: '64px' }],
      },
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: 'var(--color-card)',
        cardForeground: 'var(--color-card-foreground)',
        popover: 'var(--color-popover)',
        popoverForeground: 'var(--color-popover-foreground)',
        primary: 'var(--color-primary)',
        primaryForeground: 'var(--color-primary-foreground)',
        secondary: 'var(--color-secondary)',
        secondaryForeground: 'var(--color-secondary-foreground)',
        muted: 'var(--color-muted)',
        mutedForeground: 'var(--color-muted-foreground)',
        accent: 'var(--color-accent)',
        accentForeground: 'var(--color-accent-foreground)',
        destructive: 'var(--color-destructive)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        chart1: 'var(--color-chart-1)',
        chart2: 'var(--color-chart-2)',
        chart3: 'var(--color-chart-3)',
        chart4: 'var(--color-chart-4)',
        chart5: 'var(--color-chart-5)',
        sidebar: 'var(--color-sidebar)',
        sidebarForeground: 'var(--color-sidebar-foreground)',
        sidebarPrimary: 'var(--color-sidebar-primary)',
        sidebarPrimaryForeground: 'var(--color-sidebar-primary-foreground)',
        sidebarAccent: 'var(--color-sidebar-accent)',
        sidebarAccentForeground: 'var(--color-sidebar-accent-foreground)',
        sidebarBorder: 'var(--color-sidebar-border)',
        sidebarRing: 'var(--color-sidebar-ring)',
      },
      borderRadius: {
        sm: 6,
        md: 8,
        lg: 10,
        xl: 14,
        '2xl': 18,
        '3xl': 22,
        '4xl': 26,
      },
    },
  },
  plugins: [],
};
