import { vars } from 'nativewind';

import { COLORS, type ColorSchemeType } from '@/theme/colors';

const { light, dark } = COLORS;

/** CSS variables cho NativeWind (`global.css` / `tailwind.config`). */
export const THEMES: Record<ColorSchemeType, ReturnType<typeof vars>> = {
  light: vars({
    '--color-background': light.background,
    '--color-foreground': light.foreground,
    '--color-card': light.card,
    '--color-card-foreground': light.cardForeground,
    '--color-popover': light.popover,
    '--color-popover-foreground': light.popoverForeground,
    '--color-primary': light.primary,
    '--color-primary-foreground': light.primaryForeground,
    '--color-secondary': light.secondary,
    '--color-secondary-foreground': light.secondaryForeground,
    '--color-muted': light.muted,
    '--color-muted-foreground': light.mutedForeground,
    '--color-accent': light.accent,
    '--color-accent-foreground': light.accentForeground,
    '--color-destructive': light.destructive,
    '--color-border': light.border,
    '--color-input': light.input,
    '--color-ring': light.ring,
    '--color-chart-1': light.chart1,
    '--color-chart-2': light.chart2,
    '--color-chart-3': light.chart3,
    '--color-chart-4': light.chart4,
    '--color-chart-5': light.chart5,
    '--color-sidebar': light.sidebar,
    '--color-sidebar-foreground': light.sidebarForeground,
    '--color-sidebar-primary': light.sidebarPrimary,
    '--color-sidebar-primary-foreground': light.sidebarPrimaryForeground,
    '--color-sidebar-accent': light.sidebarAccent,
    '--color-sidebar-accent-foreground': light.sidebarAccentForeground,
    '--color-sidebar-border': light.sidebarBorder,
    '--color-sidebar-ring': light.sidebarRing,
  }),
  dark: vars({
    '--color-background': dark.background,
    '--color-foreground': dark.foreground,
    '--color-card': dark.card,
    '--color-card-foreground': dark.cardForeground,
    '--color-popover': dark.popover,
    '--color-popover-foreground': dark.popoverForeground,
    '--color-primary': dark.primary,
    '--color-primary-foreground': dark.primaryForeground,
    '--color-secondary': dark.secondary,
    '--color-secondary-foreground': dark.secondaryForeground,
    '--color-muted': dark.muted,
    '--color-muted-foreground': dark.mutedForeground,
    '--color-accent': dark.accent,
    '--color-accent-foreground': dark.accentForeground,
    '--color-destructive': dark.destructive,
    '--color-border': dark.border,
    '--color-input': dark.input,
    '--color-ring': dark.ring,
    '--color-chart-1': dark.chart1,
    '--color-chart-2': dark.chart2,
    '--color-chart-3': dark.chart3,
    '--color-chart-4': dark.chart4,
    '--color-chart-5': dark.chart5,
    '--color-sidebar': dark.sidebar,
    '--color-sidebar-foreground': dark.sidebarForeground,
    '--color-sidebar-primary': dark.sidebarPrimary,
    '--color-sidebar-primary-foreground': dark.sidebarPrimaryForeground,
    '--color-sidebar-accent': dark.sidebarAccent,
    '--color-sidebar-accent-foreground': dark.sidebarAccentForeground,
    '--color-sidebar-border': dark.sidebarBorder,
    '--color-sidebar-ring': dark.sidebarRing,
  }),
};
